[rocm-libraries] ROCm/rocm-libraries#8353 (commit 08a7c20)
Revert "Replace download project with fetchcontent"

Reverts ROCm/rocm-libraries#6573
fixes: https://github.com/ROCm/rocm-libraries/issues/8352

```
FAILED: _deps/googlebench-build/src/CMakeFiles/benchmark.dir/string_util.cc.obj
B:/build/math-libs/rocThrust/build/_deps/googlebench-src/src/string_util.cc:158:46:
error: diagnostic behavior may be improved by adding the 'format(printf, 1, 2)'
attribute to the declaration of 'StrFormat' [-Werror,-Wmissing-format-attribute]
1 error generated.
```